package no.nav.k9.sak.domene.arbeidsforhold.impl;

public enum AksjonspunktÅrsak {
    MANGLENDE_INNTEKTSMELDING,
    INNTEKTSMELDING_UTEN_ARBEIDSFORHOLD,
    ENDRING_I_ARBEIDSFORHOLDS_ID,
    OVERGANG_ARBEIDSFORHOLDS_ID_UNDER_YTELSE
}
