package no.nav.foreldrepenger.behandling.hendelse.prosess;

public enum EventHendelse {
    AKSJONSPUNKT_OPPRETTET,
    AKSJONSPUNKT_UTFØRT,
    AKSJONSPUNKT_TILBAKEFØR,
    AKSJONSPUNKT_AVBRUTT,
    AKSJONSPUNKT_HAR_ENDRET_BEHANDLENDE_ENHET,
    BEHANDLINGSKONTROLL_EVENT
}
