package no.nav.ung.sak.tilgangskontroll.tilganger;

public enum IkkeTilgangÅrsak {
    HAR_IKKE_TILGANG_TIL_APPLIKASJONEN,
    ER_IKKE_BESLUTTER,
    ER_IKKE_SAKSBEHANDLER,
    ER_IKKE_OVERSTYRER,
    ER_IKKE_VEILEDER_ELLER_SAKSBEHANDLER,
    ER_IKKE_DRIFTER,
    KAN_IKKE_BESLUTTE_EGEN_SAK,
    HAR_IKKE_TILGANG_TIL_KODE6_PERSON,
    HAR_IKKE_TILGANG_TIL_KODE7_PERSON,
    HAR_IKKE_TILGANG_TIL_EGEN_ANSATT,
    FEIL_AKSJONSPUNKT_FOR_BESLUTTER,
    FEIL_AKSJONSPUNKT_FOR_SAKSBEHANDLING,
    BEHANDLINGEN_ER_LUKKET,
    TEKNISK_FEIL,
}
