package no.nav.k9.sak.ytelse.pleiepengerbarn.vilkår.forlengelse.beregning;

public enum EndringsårsakUtbetaling {
    ENDRET_OPPLYSNINGER_OM_TILSYN_PLEIETRENGENDE,
    ENDRING_I_REFUSJONSKRAV,
    SØKNAD_FRA_BRUKER,
    ENDRING_I_PERSONOPPLYSNING_PLEIETRENGENDE,
    ENDRING_I_PERSONOPPLYSNING_SØKER,
    ENDRING_I_DATO_NYE_UTTAK_REGLER,
    ENDRING_I_UTTAK_OVERSTYRING,
    ENDRET_FORDELING_PROSESS_TRIGGER,
    GJENOPPTAR_UTSATT_BEHANDLING_PROSESS_TRIGGER,
    ENDRING_FRA_ANNEN_OMSORGSPERSON_PROSESS_TRIGGER

}
