name: Generate typescript client
description: Generate typescript client from openapi spec.
env:
  RESULT_DIR: web/target/ts-client # Generated code is put here
inputs:
  openapiVersion:
    description: The openapi version extracted from openapi.json
    required: true
  patchVersion:
    description: 'The <TIMESTAMP>-<SHA> value used as a tag of the version for deployment.'
    required: true
outputs:
  resultDir:
    description: Directory in which the generated typescript client package was written
    value: ${{ env.RESULT_DIR }}

runs:
  using: 'composite'
  steps:
    - name: Typescript generate
      id: typescript-generate
      uses: navikt/openapi-ts-clientmaker@main
      with:
        openapi-spec-file: web/src/main/resources/openapi-ts-client/k9-sak.openapi.json
        package-json-file: web/src/main/resources/openapi-ts-client/package.json
        package-json-version: "${{ env.PACKAGE_JSON_VERSION }}"
        out-dir: "${{ env.RESULT_DIR }}"
        client-name: K9SakClient
      env:
        PACKAGE_JSON_VERSION: "${{ inputs.openapiVersion }}.${{ inputs.patchVersion }}"
