package no.nav.ung.sak.oppgave.varsel;

public enum YtelseType {
    SYKEPENGER,
    FORELDREPENGER,
    SVANGERSKAPSPENGER,
    OPPLÆRINGSPENGER,
    OMSORGSPENGER,
    PLEIEPENGER_SYKT_BARN,
    PLEIEPENGER_NÆRSTÅENDE,
    ARBEIDSAVKLARINGSPENGER,
    DAGPENGER,
    KVALIFISERINGSSTØNAD,
    TILTAKSPENGER,
    ANNET
}

