name: Generate openapi
description: Generate new openapi spec, and generate typescript from it.
inputs:
  patchVersion:
    description: The TAG environment variable from the master build workflow (TIMESTAMP-SHA)
    required: true


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        path: k9-sak
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Openapi generate
      shell: bash
      working-directory: k9-sak
      env:
        GH_ACCESS_TOKEN: ${{ secrets.READER_TOKEN }}
      run: |
        mvn install -e --batch-mode --settings ./.github/.m2/settings.xml -DskipTests=true
        mvn exec:java --projects web -e --batch-mode --settings ./.github/.m2/settings.xml

    - name: Cross repo token
      uses: navikt/github-app-token-generator@v1.2
      id: get-token
      with:
        private-key: ${{ secrets.K9SAKSBEHANDLING_PRIVATE_KEY }}
        app-id: ${{ secrets.K9SAKSBEHANDLING_APP_ID }}

    - name: Sjekk ut k9-sak-typescript-client
      uses: actions/checkout@v4
      with:
        repository: navikt/k9-sak-typescript-client
        ref: 'k9-sak-workflow' # Maybe just use main later
        token: ${{ steps.get-token.outputs.token }}
        path: k9-sak-typescript-client
        fetch-depth: 0

    - name: Kopier ny openapi spec til klient
      shell: bash
      working-directory: k9-sak
      # Copy the generated openapi spec json to k9-sak-typescript-client, and extract its version number
      run: |
        cp web/target/k9-sak.openapi.json ../k9-sak-typescript-client/src/
        echo "OPENAPI_VERSION=$(jq --exit-status --raw-output '.info.version | capture("^(?<major>\\d+)\\.(?<minor>\\d+)$") | .major + "." + .minor' ./web/target/k9-sak.openapi.json || echo 'FEIL')" >> $GITHUB_ENV
    - name: Feilsjekk OPENAPI_VERSION
      if: "${{ env.OPENAPI_VERSION == 'FEIL'}}"
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('fant ikkje korrekt openapi version frå k9-sak.openapi.json')
    - name: Push ny openapi spec til klient repo
      if: success()
      shell: bash
      working-directory: k9-sak-typescript-client
      env:
        GIT_USER_NAME: "${{ github.actor }}"
        GIT_USER_EMAIL: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        GITHUB_TOKEN: "${{ steps.get-token.outputs.token }}"
        VERSION_TAG: "v${{ env.OPENAPI_VERSION }}.${{ inputs.patchVersion }}"
      # git commit, tag og push ny k9-sak.openapi.json til k9-sak-typescript-client
      # NB: git diff framfor gjere at det berre blir gjort viss det faktisk er endringer i ny generert k9-sak.openapi.json
      run: |
        git config user.email "$GIT_USER_EMAIL"
        git config user.name "$GIT_USER_NAME"
        git diff --quiet || (git add -A && git commit -m "k9-sak.openapi.json updated from k9-sak" && git tag "${VERSION_TAG}" && git push origin "${VERSION_TAG}")
