package no.nav.k9.kodeverk.beregningsgrunnlag;

public class BeregningAvklaringsbehovKodeDefinition {

    static final String AUTO_VENT_PÅ_INNTEKT_RAPPORTERINGSFRIST_KODE = "AUTO_VENT_PAA_INNTKT_RAP_FRST";
    static final String AUTO_VENT_PÅ_SISTE_AAP_ELLER_DP_MELDEKORT_KODE = "AUTO_VENT_PAA_SISTE_AAP_DP_MELDKRT";

    static final String AUTO_VENT_FRISINN_KODE = "AUTO_VENT_FRISINN";

    static final String OVERSTYRING_AV_BEREGNINGSAKTIVITETER_KODE = "OVST_BEREGNINGSAKTIVITETER";
    static final String OVERSTYRING_AV_BEREGNINGSGRUNNLAG_KODE = "OVST_INNTEKT";

    static final String FASTSETT_BEREGNINGSGRUNNLAG_ARBEIDSTAKER_FRILANS_KODE = "FASTSETT_BG_AT_FL";
    static final String FORDEL_BEREGNINGSGRUNNLAG_KODE = "FORDEL_BG";
    static final String FASTSETT_BEREGNINGSGRUNNLAG_TIDSBEGRENSET_ARBEIDSFORHOLD_KODE = "FASTSETT_BG_TB_ARB";
    static final String FASTSETT_BEREGNINGSGRUNNLAG_FOR_SN_NY_I_ARBEIDSLIVET_KODE = "FASTSETT_BG_SN_NY_I_ARB_LIVT";
    static final String AVKLAR_AKTIVITETER_KODE = "AVKLAR_AKTIVITETER";

    static final String VURDER_VARIG_ENDRET_ELLER_NYOPPSTARTET_NÆRING_SELVSTENDIG_NÆRINGSDRIVENDE_KODE = "VURDER_VARIG_ENDRT_NYOPPSTR_NAERNG_SN";
    static final String VURDER_VARIG_ENDRET_ARBEIDSSITUASJON_KODE = "VURDER_VARIG_ENDRT_ARB_SITSJN_MDL_INAKTV";
    static final String VURDER_FAKTA_FOR_ATFL_SN_KODE = "VURDER_FAKTA_ATFL_SN";
    static final String VURDER_REFUSJON_BERGRUNN_KODE = "VURDER_REFUSJONSKRAV";
    static final String VURDER_NYTT_INNTKTSFRHLD_KODE = "VURDER_NYTT_INNTKTSFRHL";
    static final String VURDER_REPRESENTERER_STORTINGET_KODE = "VURDER_REPRSNTR_STORTNGT";

    static final String FASTSETT_BEREGNINGSGRUNNLAG_SELVSTENDIG_NÆRINGSDRIVENDE_KODE = "FASTSETT_BG_SN";





    private BeregningAvklaringsbehovKodeDefinition() {
    }
}
