apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-sak
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /k9/sak/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
    # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness:
    path: /k9/sak/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /k9/sak/internal/metrics/prometheus
  resources:
    limits:
      cpu: "4000m"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "1024Mi"
  ingresses:
    - "https://k9-sak.nais.adeo.no/"
  kafka:
    pool: "nav-prod"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9sak
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: /serviceuser/data/prod/srvssolinux
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-sak/k9saksbehandling
  sidecar: true
  env:
    - name: TZ
      value: "Europe/Oslo"
    - name: APP_NAME
      value: "K9SAK"

    - name: DEFAULTDS_USERNAME
      value: k9-sak
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-sak

    # Appdynamics
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: PROD

    # Integrasjoner (Kafka)
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_DOKUMENTBESTILLING_TOPIC
      value: privat-k9-dokumenthendelse
    - name: KAFKA_INFOTRYGDFEED_TOPIC
      value: privat-k9-infotrygdFeedHendelse
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: privat-familie-vedtakFattet-v1
    - name: KAFKA_VEDTAKHENDELSE_TOPIC
      value: privat-k9-vedtakhendelse
    - name: KAFKA_STONADSTATISTIKK_TOPIC
      value: k9saksbehandling.aapen-k9-stonadstatistikk-v1
    - name: KAFKA_BRUKERDIALOGINNSYN_TOPIC
      value: dusseldorf.privat-k9-sak-innsyn-v1

    # Baseurl
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.adeo.no
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443

    # Loadbalancerconfig
    - name: LOADBALANCER_URL
      value: https://app.adeo.no

    # LDAP
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"

    # PDL
    - name: PDL_TEMA
      value: OMS

    # Restservice Generelle
    - name: INFOTRYGD_HENDELSER_API_URL
      value: http://infotrygd-hendelser.default/infotrygd/hendelser
    - name: FPABAKUS_URL
      value: http://fpabakus.default/fpabakus
    - name: FTKALKULUS_URL
      value: http://ftkalkulus.k9saksbehandling/ftkalkulus
    - name: ABAKUS_CALLBACK_URL
      value: http://k9-sak.k9saksbehandling/k9/sak/api/registerdata/iay/callback
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.teamabac/application/authorize
    - name: K9_OPPDRAG_PROXY_URL
      value: https://app.adeo.no/k9/oppdrag/api
    - name: ARBEIDSFORDELING_RS_URL
      value: https://app.adeo.no/norg2/api/v1/arbeidsfordeling/enheter
    - name: OPPGAVE_RS_URI
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: MEDL2_RS_URL
      value: https://app.adeo.no/medl2/api/v1/medlemskapsunntak
    - name: PDL_BASE_URL
      value: http://pdl-api.default/graphql
    - name: ORGANISASJON_RS_URL
      value: https://modapp.adeo.no/ereg/api/v1/organisasjon
    - name: K9_FORMIDLING_DOKUMENTDATA_URL
      value: http://k9-formidling-dokumentdata.k9saksbehandling/k9/formidling/dokumentdata
    - name: K9_OPPDRAG_DIREKTE_URL
      value: http://k9-oppdrag.default/k9/oppdrag/api
    - name: K9_TILBAKE_DIREKTE_URL
      value: http://k9-tilbake.default/k9/tilbake/api
    - name: K9_FORMIDLING_URL
      value: http://k9-formidling.k9saksbehandling/k9/formidling
    - name: K9_PUNSJ_URL
      value: https://k9-punsj.nais.adeo.no/api
    - name: INFOTRYGD_BS_BASE_URI
      value: https://k9-infotrygd.intern.nav.no

    # Restservice OMS spesifikt
    - name: K9_OMS_AARSKVANTUM_URL
      value: http://k9-aarskvantum.default
    - name: K9_OMS_UTVIDETRETT_URL
      value: https://omsorgsdager.intern.nav.no/api

    # Restservice PSB spesifikt
    - name: K9_PSB_UTTAK_URL
      value: http://pleiepenger-barn-uttak.k9saksbehandling/pleiepenger-barn-uttak

    # Graphql services
    - name: SAF_BASE_URL
      value: http://saf.teamdokumenthandtering

    # Sikkerhet:
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: OIDC_STS_ISSUER_URL
      value: https://security-token-service.nais.adeo.no
    - name: OIDC_STS_JWKS_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/jwks
    - name: OPENIDCONNECT_ISSOHOST
      value: https://isso.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOISSUER
      value: https://isso.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOJWKS
      value: https://isso.adeo.no:443/isso/oauth2/connect/jwk_uri
    - name: OIDC_OPENAM_CLIENT_ID
      value: k9-sak-p

    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.k9.drift"

    # metrics
    - name: SENSU_HOST
      value: "sensu.nais"
    - name: SENSU_PORT
      value: "3030"

    # Feature-flag
    - name: OMP_IM_SJEKK_FORSTE_FRAVAERSDAG
      value: "false"
    - name: PSB_OPPG_OPPTJENING_PRIORITERING
      value: "false"
    - name: AUTOMATISK_VEDTAK_OMP_SOKNAD
      value: "false"
    - name: FRISINN_FLERE_SOKNADER_SAMME_DAG
      value: "false"
    - name: TOTRINN_TEMP_DEAKTIVERT
      value: "true"
    - name: "AKSJONSPUNKT_7035_ENABLED"
      value: "true"
    - name: K9TILBAKE_AKTIVERT
      value: "true"
    - name: ENABLE_UTLEDET_ENDRINGSPERIODE
      value: "true"
    - name: ENABLE_RELEVANT_SYKDOMSPERIODE
      value: "true"
    - name: ENABLE_STONADSTATISTIKK
      value: "true"
    - name: PSB_UTTAK_UNNTAK_AKTIVITETER
      value: "AFMX0|2021-03-01"
    - name: MAP_ALLE_KRAV
      value: "true"
    - name: PSB_ENABLE_BEKREFT_UTTAK
      value: "true"
    - name: DISABLE_VURDER_TILBAKETREKK
      value: "true"
    - name: PSB_INFOTRYGD_MIGRERING
      value: "true"
    - name: FORLENGELSE_OPPTJENING_ENABLET
      value: "true"
    - name: FORLENGELSE_BEREGNING_ENABLET
      value: "false"
    - name: BEHANDLINGID_DOKUMENTLIST_ENABLET
      value: "true"
    - name: PERIODER_KANT_I_KANT_VURDERER_ENABLET
      value: "true"
    - name: VEDTAK_PERSISTER_ENDRET_PERIODE
      value: "true"
    - name: K9_RAPID_AIVEN
      value: "false"
    - name: ENABLE_SAMTIDIG_UTTAK_RELEVANTSJEKK
      value: "true"
    - name: KOMPLETTHET_SKIP_VED_AVSLAG_SOKNADSFRIST
      value: "false"

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-sak"

    - name: PIP_USERS
      value: "srvPDP,srvk9-tilbake,srvsaf"

    # Pleiepenger infotrygd migrering
    - name: INFOTRYGD_MIGRERING_TILLATELSER
      value: "K137924,N106674,H137477,N130802,N140249,A100265,D101758,E151154,A147438"

    # FRISINN NYE REGLER 2022
    - name: FRISINN_NYTT_STP_TOGGLE
      value: "false"
