apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-sak
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /k9/sak/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
    # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness:
    path: /k9/sak/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /k9/sak/internal/metrics/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
  resources:
    limits:
      cpu: "4000m"
      memory: "4096Mi"
    requests:
      cpu: "500m"
      memory: "4096Mi"
  ingresses:
    - "https://k9-sak.nais.adeo.no/"
    - "https://k9-sak.prod-fss-pub.nais.io"
  kafka:
    pool: "nav-prod"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9sak
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: /serviceuser/data/prod/srvssolinux
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-sak/k9saksbehandling
  azure:
    application:
      enabled: true
      replyURLs:
        - "https://k9.intern.nav.no/k9/sak/cb"
      claims:
        extra:
          - "NAVident"
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: k9-los-api
        - application: k9-fordel
        - application: k9-sak
        - application: k9-tilbake
        - application: k9-klage
        - application: k9-formidling
        - application: k9-formidling-dokumentdata
        - application: k9-punsj
        - application: k9-abakus
        - application: k9-punsjbolle
          namespace: omsorgspenger
          cluster: prod-gcp
        - application: k9-sak-innsyn-api
          namespace: dusseldorf
          cluster: prod-gcp

  env:
    - name: TZ
      value: "Europe/Oslo"
    - name: APP_NAME
      value: "K9SAK"

    - name: DEFAULTDS_USERNAME
      value: k9-sak
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-sak

    # open telemetry
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=k9-sak,service.namespace=k9saksbehandling,deployment.environment=p,nais.backend=elastic-apm;grafana-lgtm"

    # Integrasjoner (Kafka)
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_AKSJONSPUNKTHENDELSE_AIVEN_TOPIC
      value: k9saksbehandling.k9sak-aksjonspunkthendelse
    - name: KAFKA_DOKUMENTBESTILLING_AIVEN_TOPIC
      value: k9saksbehandling.k9-dokumenthendelse-v1
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: teamforeldrepenger.familie-vedtakfattet-v1
    - name: KAFKA_VEDTAKHENDELSE_TOPIC
      value: privat-k9-vedtakhendelse
    - name: KAFKA_VEDTAKHENDELSE_AIVEN_TOPIC
      value: k9saksbehandling.k9-vedtakhendelse
    - name: KAFKA_STONADSTATISTIKK_TOPIC
      value: k9saksbehandling.aapen-k9-stonadstatistikk-v1
    - name: KAFKA_BRUKERDIALOGINNSYN_TOPIC
      value: dusseldorf.privat-k9-sak-innsyn-v1
    - name: KAFKA_PRODUKSJONSSTYRING_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2
    - name: KAFKA_INFOTRYGDFEED_AIVEN_TOPIC
      value: k9saksbehandling.k9-infotrygd-feed-hendelse

    # Baseurl
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.adeo.no
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443

    # Loadbalancerconfig
    - name: LOADBALANCER_URL
      value: https://k9.intern.nav.no

    # LDAP
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"

    # PDL
    - name: PDL_TEMA
      value: OMS

    # Restservice Generelle
    - name: K9ABAKUS_URL
      value: http://k9-abakus.k9saksbehandling/k9/abakus
    - name: K9ABAKUS_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-abakus/.default
    - name: FTKALKULUS_URL
      value: http://ftkalkulus.k9saksbehandling/ftkalkulus
    - name: FTKALKULUS_SCOPE
      value: api://prod-fss.k9saksbehandling.ftkalkulus/.default
    - name: ABAKUS_CALLBACK_URL
      value: http://k9-sak.k9saksbehandling/k9/sak/api/registerdata/iay/callback
    - name: ABAKUS_CALLBACK_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-sak/.default
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling/application/authorize
    - name: K9_OPPDRAG_PROXY_URL
      value: /k9/oppdrag/api
    - name: ARBEIDSFORDELING_RS_URL
      value: https://app.adeo.no/norg2/api/v1/arbeidsfordeling/enheter
    - name: OPPGAVE_RS_URI
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: OPPGAVE_RS_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: MEDL2_RS_URL
      value: https://medlemskap-medl-api.intern.nav.no/api/v1/medlemskapsunntak
    - name: MEDL2_RS_SCOPE
      value: api://prod-fss.team-rocket.medlemskap-medl-api/.default
    - name: PDL_BASE_URL
      value: http://pdl-api.pdl/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: ORGANISASJON_RS_URL
      value: https://modapp.adeo.no/ereg/api/v1/organisasjon
    - name: K9_FORMIDLING_DOKUMENTDATA_URL
      value: http://k9-formidling-dokumentdata.k9saksbehandling/k9/formidling/dokumentdata
    - name: K9_FORMIDLING_DOKUMENTDATA_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-formidling-dokumentdata/.default
    - name: K9_OPPDRAG_DIREKTE_URL
      value: http://k9-oppdrag.k9saksbehandling/k9/oppdrag/api
    - name: K9_OPPDRAG_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-oppdrag/.default
    - name: K9_TILBAKE_DIREKTE_URL
      value: http://k9-tilbake.k9saksbehandling/k9/tilbake/api
    - name: K9_TILBAKE_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-tilbake/.default
    - name: K9_FORMIDLING_URL
      value: http://k9-formidling.k9saksbehandling/k9/formidling
    - name: K9_FORMIDLING_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-formidling/.default
    - name: K9_PUNSJ_URL
      value: https://k9-punsj.intern.nav.no/api
    - name: K9_PUNSJ_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-punsj/.default
    - name: INFOTRYGD_BS_BASE_URI
      value: http://k9-infotrygd-grunnlag-paaroerende-sykdom.k9saksbehandling
    - name: K9_INFOTRYGD_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-infotrygd-grunnlag-paaroerende-sykdom/.default
    - name: ARBEID_OG_INNTEKT_BASE_URL
      value: https://arbeid-og-inntekt.nais.adeo.no
    - name: K9INNTEKTSMELDING_URL
      value: https://k9-inntektsmelding.intern.nav.no/k9/inntektsmelding
    - name: K9INNTEKTSMELDING_SCOPE
      value: api://prod-gcp.k9saksbehandling.k9-inntektsmelding/.default
    - name: K9FORDEL_URL
      value: http://k9-fordel.k9saksbehandling/k9/fordel/api
    - name: K9FORDEL_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-fordel/.default

    # Restservice OMS spesifikt
    - name: K9_OMS_AARSKVANTUM_URL
      value: http://k9-aarskvantum.k9saksbehandling
    - name: K9_OMS_AARSKVANTUM_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-aarskvantum/.default

    # Restservice PSB spesifikt
    - name: K9_PSB_UTTAK_URL
      value: http://pleiepenger-barn-uttak.k9saksbehandling/pleiepenger-barn-uttak
    - name: K9_PSB_UTTAK_SCOPE
      value: api://prod-fss.k9saksbehandling.pleiepenger-barn-uttak/.default

    # Graphql services
    - name: SAF_BASE_URL
      value: http://saf.teamdokumenthandtering
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default

    # Sikkerhet:
    - name: APP_AUTH_SCHEMA_AZUREAD_ADDITIONAL_PATHS
      value: "/k9/formidling/dokumentdata,api://prod-fss.k9saksbehandling.k9-formidling-dokumentdata/.default;/k9/formidling,api://prod-fss.k9saksbehandling.k9-formidling/.default"
    - name: APP_AUTH_SCHEMA_AZUREAD_OPTIONAL_PATHS
      value: "/k9/klage,api://prod-fss.k9saksbehandling.k9-klage/.default;/k9/tilbake,api://prod-fss.k9saksbehandling.k9-tilbake/.default;/k9/oppdrag,api://prod-fss.k9saksbehandling.k9-oppdrag/.default"
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: OIDC_STS_HOST_URL
      value: https://security-token-service.nais.adeo.no
    - name: CLIENT_SCOPE
      value: "api://prod-fss.k9saksbehandling.k9-sak/.default"
    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.k9.drift"

    # metrics
    - name: SENSU_HOST
      value: "sensu.nais"
    - name: SENSU_PORT
      value: "3030"

    # Feature-flag
    - name: PSB_UTTAK_UNNTAK_AKTIVITETER
      value: "AFMX0|2021-03-01"
    - name: UKESMOERING_OMSORGSTILBUD_FOM_DATO
      value: "2023-01-02"
    - name: IKKE_YRKESAKTIV_UTEN_SPEILING
      value: "false"
    - name: OMP_NULL_HELG_I_KRAVPERIODER
      value: "false"
    - name: ENABLE_DATO_NY_REGEL_UTTAK
      value: "false"
    - name: FJERN_VILKARSPERIODER_BEREGNING
      value: "false"
    - name: VALIDER_KALKULUS_REFERANSER
      value: "false"
    - name: AVKLAR_ARBEIDSFORHOLD_REUTLED_VED_REVURDERING
      value: "false"
    - name: OMP_RELEVANT_ENDRING_UTLEDNING
      value: "false"
    - name: KODEVERK_SOM_STRING_TOPICS
      value: "false"
    - name: KODEVERK_AKTIVER_KALKULUS_STRING
      value: "false"
    - name: INAKTIV_VED_8_47_B
      value: "false"
    - name: SEND_INNTEKTSMELDING_FORESPORSEL
      value: "false"
    - name: OMP_RAMMEVEDTAK_SAMMENSTILLNG_AARSKVANTUM
      value: "false"
    - name: ALDERSVILKAR_I_KRONISK_SYK
      value: "true"
    - name: HASTEMERKNAD_LOS_KAFKA_ENABLED
      value: "false"

    # Konfigurasjoner
    - name: FLYWAY_REPAIR_ON_FAIL
      value: "false"
    - name: RESTART_APP_ON_ERROR
      value: "true"

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-sak"

    - name: PIP_USERS
      value: "srvPDP,srvk9-tilbake,srvsaf,srvk9-abakus"
