package no.nav.ung.sak.kontrakt.oppgaver;

public enum OppgaveType {
    BEKREFT_ENDRET_STARTDATO,
    BEKREFT_ENDRET_SLUTTDATO,
    BEKREFT_ENDRET_PERIODE,
    BEKREFT_FJERNET_PERIODE,
    BEKREFT_AVVIK_REGISTERINNTEKT,
    RAPPORTER_INNTEKT,
    SØK_YTELSE,
}
