package no.nav.ung.sak.kontrakt.behandling;

public enum BehandlingVisningsnavn {
    BEREGNING_AV_HØY_SATS,
    ENDRING_AV_BARNETILLEGG,
    BRUKERS_DØDSFALL,
    UNGDOMSPROGRAMENDRING,
    OPPHØR_VED_MAKSDATO,
    OPPHØR_OPPHEVET,
    KONTROLL_AV_INNTEKT,

    INGEN_RELEVANT_BEHANDLINGÅRSAK,
    FLERE_BEHANDLINGÅRSAKER
}
