create table if not exists  SO_SOEKNAD_ANGITT_PERSON(
ID BIGINT NOT NULL,
SOEKNAD_ID BIGINT NOT NULL,
ROLLE VARCHAR(100) NOT NULL,
AKTOER_ID VARCHAR(50),
NAVN VARCHAR(200),
FOEDSELSDATO DATE,
SITUASJON_KODE VARCHAR(100),
TILLEGGSOPPLYSNINGER TEXT,
VERSJON BIGINT DEFAULT 0 NOT NULL,
OPPRETTET_AV VARCHAR(20) DEFAULT 'VL' NOT NULL,
OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
ENDRET_AV VARCHAR(20),
ENDRET_TID TIMESTAMP(3)
);




create sequence if not exists SEQ_SOEKNAD_ANGITT_PERSON increment by 50 minvalue 1000000;