DELETE FROM FAGSAK_PROSESS_TASK WHERE prosess_task_id='1209150';

UPDATE PROSESS_TASK
SET STATUS='KJOERT'
WHERE STATUS <> 'FERDIG'
  AND BLOKKERT_AV IN (
    SELECT p.ID
    FROM PROSESS_TASK p
    WHERE p.TASK_GRUPPE = (
      SELECT q.TASK_GRUPPE
      FROM PROSESS_TASK q
      WHERE q.ID=1209150
    )
  );

UPDATE PROSESS_TASK
SET STATUS='KJOERT'
WHERE STATUS <> 'FERDIG'
  AND TASK_GRUPPE = (
    SELECT TASK_GRUPPE
    FROM PROSESS_TASK
    WHERE ID=1209150
  );
