create table if not exists SYKDOM_GRUNNLAG_DOKUMENT
(
    SYKDOM_GRUNNLAG_ID          BIGINT                      NOT NULL,
    SYKDOM_DOKUMENT_ID          BIGINT                      NOT NULL,

    OPPRETTET_AV                VARCHAR(20)  DEFAULT 'VL'              NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_SYKDOM_GRUNNLAG_DOKUMENT_01
        FOREIGN KEY(SYKDOM_GRUNNLAG_ID) REFERENCES SYKDOM_GRUNNLAG(ID),
    CONSTRAINT FK_SYKDOM_GRUNNLAG_DOKUMENT_02
        FOREIGN KEY(SYKDOM_DOKUMENT_ID) REFERENCES SYKDOM_DOKUMENT(ID),
    UNIQUE(SYKDOM_GRUNNLAG_ID, SYKDOM_DOKUMENT_ID)
);
create sequence if not exists SEQ_SYKDOM_GRUNNLAG_DOKUMENT increment by 5 minvalue 1000000;
