DROP TABLE SOEKNAD_VEDLEGG;
DROP SEQUENCE SEQ_SOEKNAD_VEDLEGG;
DROP TABLE SO_SOEKNAD_ANGITT_PERSON;
DROP SEQUENCE SEQ_SOEKNAD_ANGITT_PERSON;

ALTER TABLE SO_SOEKNAD
    DROP COLUMN IF EXISTS bruker_rolle,
    DROP COLUMN IF EXISTS er_endringssoeknad,
    DROP COLUMN IF EXISTS tilleggsopplysninger,
    DROP COLUMN IF EXISTS fom,
    DROP COLUMN IF EXISTS tom,
    RENAME COLUMN soeknadsdato TO startdato,;

