alter table BR_RESULTAT_BEHANDLING add OVERSTYRT_BEREGNINGSRESULTAT_ID BIGINT;
comment on column BR_RESULTAT_BEHANDLING.OVERSTYRT_BEREGNINGSRESULTAT_ID is 'FK: BEREGNINGSRESULTAT_FP. Tilkjent ytelse er overstyrt av saksbehandler';
