CREATE TABLE IF NOT EXISTS RS_MAN_VILKARSVURDERING
(
    ID            BIGINT                                 NOT NULL PRIMARY KEY,
    FRITEKST      TEXT                                   NOT NULL,
    VERSJON       BIGINT       DEFAULT 0                 NOT NULL,
    OPPRETTET_AV  VARCHAR(20)  DEFAULT 'VL'              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV     VARCHAR(20),
    ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_RS_MAN_VILKARSVURDERING INCREMENT BY 50 MINVALUE 1000000;


ALTER TABLE RS_VILKARS_RESULTAT
    ADD IF NOT EXISTS MANUELL_VILKARSVURDERING_ID BIGINT,
    ADD CONSTRAINT FK_RS_VILKARS_RESULTAT_3 FOREIGN KEY (MANUELL_VILKARSVURDERING_ID) REFERENCES RS_MAN_VILKARSVURDERING (ID);

CREATE INDEX IF NOT EXISTS RS_VILKARS_RESULTAT_MANUELL_VILKARSVURDERING_ID_INDEX
    ON RS_VILKARS_RESULTAT (MANUELL_VILKARSVURDERING_ID);
