ALTER TABLE IF EXISTS UNG_GR_SOEKNADGRUNNLAG RENAME COLUMN RELEVANTE_SOEKNADER_ID TO RELEVANTE_STARTDATOER_ID;
ALTER TABLE IF EXISTS UNG_GR_SOEKNADGRUNNLAG RENAME COLUMN OPPGITTE_SOEKNADER_ID TO OPPGITTE_STARTDATOER_ID;
ALTER TABLE IF EXISTS UNG_GR_SOEKNADGRUNNLAG RENAME TO UNG_GR_STARTDATO;
ALTER SEQUENCE IF EXISTS SEQ_UNG_GR_SOEKNADGRUNNLAG RENAME TO SEQ_UNG_GR_STARTDATO;

ALTER TABLE IF EXISTS UNG_SOEKNADER RENAME TO UNG_STARTDATOER;
ALTER SEQUENCE IF EXISTS SEQ_UNG_SOEKNADER RENAME TO SEQ_UNG_STARTDATOER;

ALTER TABLE IF EXISTS UNG_SOEKT_STARTDATO RENAME COLUMN UNG_SOEKNADER_ID TO UNG_STARTDATOER_ID;

