insert into prosess_task (id, task_type, task_gruppe, neste_kjoering_etter, task_parametere)
select nextval('seq_prosess_task'), 'beregning.tilbakeTilStart',
       nextval('seq_prosess_task_gruppe'), null,
       'fagsakId=' || f.id || '
                behandlingId=' || b.id from fagsak f
                inner join behandling b on f.id = b.fagsak_id
                where f.saksnummer in (
                    '7BioU',
                    '7BLME',
                    '7BS9A',
                    '7CD0i',
                    '7CFAG',
                    '7CKJC',
                    '7CPFQ',
                    '7CZTC',
                    '7DLM2',
                    '7DM2Q',
                    '7DQZ4',
                    '7DVWW',
                    '7DWQ2',
                    '7E3Mo',
                    '7EC9S',
                    '7ELSU',
                    '7EMSY',
                    '7EP9U',
                    '7ERJS',
                    '7ES0G',
                    '7EW7U',
                    '7EX10',
                    '7EZT0',
                    '7F0CG',
                    '7F1P2',
                    '7F4JU',
                    '7F96i',
                    '7FAC6',
                    '7FEJK',
                    '7FGFM',
                    '7FH1U',
                    '7FiAA',
                    '7FK0S',
                    '7FP8A',
                    '7FZ9E',
                    '7FZDK',
                    '7G25K',
                    '7G3JK',
                    '7GC6o',
                    '7GCZU',
                    '7GFW0',
                    '7GJA8',
                    '7GJH6',
                    '7GMG4',
                    '7H29K',
                    '7HDC6',
                    '7HDJ4',
                    '7HDQ2',
                    '7HJE8',
                    '7HM4U',
                    '7HMiQ',
                    '7HN0S',
                    '7HSYo',
                    '7J7GQ',
                    '7KMJM',
                    '7KVAW',
                    '7L782',
                    '7M30i',
                    '7MZRo',
                    '7o950',
                    '7oY50',
                    '7P8ZA',
                    '7PKA8',
                    '7QTQC',
                    '7RoWK',
                    '7RR54',
                    '7RTAW',
                    '7So38',
                    '7T0XQ',
                    '7T4EQ',
                    '7T6DK',
                    '7TEQY',
                    '7ToJQ',
                    '7TXCE',
                    '7VFXo',
                    '7W2W2',
                    '7X4QK',
                    '7X7EE',
                    '7XMEo',
                    '7ZA62',
                    '7ZFHQ',
                    '816AU')
                and b.behandling_status = 'UTRED'
                and (select count(*) from behandling_steg_tilstand bst
                    where bst.behandling_id = b.id
                    and bst.behandling_steg = 'KOFAKBER'
                    and bst.aktiv = true) > 0;
