ALTER TABLE IF EXISTS UNG_GR_STARTDATO RENAME TO GR_STARTDATO;
ALTER SEQUENCE IF EXISTS SEQ_UNG_GR_STARTDATO RENAME TO SEQ_GR_STARTDATO;
ALTER INDEX IF EXISTS IDX_UNG_GR_SOEKNADGRUNNLAG_BEHANDLING RENAME TO IDX_GR_STARTDATO_BEHANDLING;
ALTER INDEX IF EXISTS IDX_GR_OPPGITT_SOEKNAD RENAME TO IDX_GR_OPPGITT_STARTDATO;
ALTER INDEX IF EXISTS IDX_GR_RELEVANT_SOEKNAD RENAME TO IDX_GR_RELEVANT_STARTDATO;
ALTER INDEX IF EXISTS UIDX_UNG_GR_SOEKNADGRUNNLAG_AKTIV_BEHANDLING RENAME TO UIDX_GR_STARTDATO_AKTIV_BEHANDLING;

ALTER TABLE IF EXISTS UNG_STARTDATOER RENAME TO STARTDATOER;
ALTER SEQUENCE IF EXISTS SEQ_UNG_STARTDATOER RENAME TO SEQ_STARTDATOER;

ALTER TABLE IF EXISTS UNG_SOEKT_STARTDATO RENAME COLUMN UNG_STARTDATOER_ID TO STARTDATOER_ID;
ALTER TABLE IF EXISTS UNG_SOEKT_STARTDATO RENAME TO SOEKT_STARTDATO;
ALTER SEQUENCE IF EXISTS SEQ_UNG_SOEKT_STARTDATO RENAME TO SEQ_SOEKT_STARTDATO;
ALTER INDEX IF EXISTS IDX_UNG_SOEKT_STARTDATO_JOURNALPOST RENAME TO IDX_SOEKT_STARTDATO_JOURNALPOST;
ALTER INDEX IF EXISTS IDX_UNG_SOEKT_STARTDATO_PERIODER RENAME TO IDX_SOEKT_STARTDATO_PERIODER;



