DELETE FROM FAGSAK_PROSESS_TASK WHERE BEHANDLING_ID='1007216';

UPDATE PROSESS_TASK
SET STATUS='KJOERT'
WHERE STATUS <> 'FERDIG'
  AND BLOKKERT_AV IN (
    SELECT p.ID
    FROM PROSESS_TASK p
    WHERE p.TASK_GRUPPE = (
      SELECT q.TASK_GRUPPE
      FROM PROSESS_TASK q
      WHERE q.ID=1090136
    )
  );

UPDATE PROSESS_TASK
SET STATUS='KJOERT'
WHERE STATUS <> 'FERDIG'
  AND TASK_GRUPPE = (
    SELECT TASK_GRUPPE
    FROM PROSESS_TASK
    WHERE ID=1090136
  );

UPDATE BEHANDLING_VEDTAK
SET vedtak_resultat_type = 'AVSLAG', iverksetting_status = 'IVERKSATT'
WHERE behandling_id = 1007216;
