ALTER TABLE PO_PERSONOPPLYSNING
    DROP COLUMN IF EXISTS sivilstand_type,
    DROP COLUMN IF EXISTS region;

DROP TABLE IF EXISTS PO_ADRESSE;
DROP TABLE IF EXISTS PO_PERSONSTATUS;
DROP TABLE IF EXISTS PO_STATSBORGERSKAP;
