CREATE TABLE PROSESS_TASK_PARTITION_DEFAULT PARTITION OF PROSESS_TASK
    DEFAULT;
create UNIQUE index PK_PROSESS_TASK_PARTITION_DEFAULT on PROSESS_TASK_PARTITION_DEFAULT (ID);
alter table PROSESS_TASK_PARTITION_DEFAULT add constraint PK_PROSESS_TASK_PARTITION_DEFAULT primary key using index PK_PROSESS_TASK_PARTITION_DEFAULT;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG PARTITION OF PROSESS_TASK
    FOR VALUES IN ('FERDIG') PARTITION BY LIST (PARTITION_KEY);
CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_01 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('01');

create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_01 on PROSESS_TASK_PARTITION_FERDIG_01 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_01 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_01 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_01;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_02 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('02');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_02 on PROSESS_TASK_PARTITION_FERDIG_02 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_02 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_02 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_02;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_03 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('03');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_03 on PROSESS_TASK_PARTITION_FERDIG_03 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_03 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_03 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_03;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_04 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('04');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_04 on PROSESS_TASK_PARTITION_FERDIG_04 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_04 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_04 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_04;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_05 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('05');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_05 on PROSESS_TASK_PARTITION_FERDIG_05 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_05 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_05 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_05;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_06 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('06');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_06 on PROSESS_TASK_PARTITION_FERDIG_06 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_06 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_06 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_06;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_07 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('07');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_07 on PROSESS_TASK_PARTITION_FERDIG_07 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_07 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_07 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_07;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_08 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('08');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_08 on PROSESS_TASK_PARTITION_FERDIG_08 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_08 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_08 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_08;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_09 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('09');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_09 on PROSESS_TASK_PARTITION_FERDIG_09 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_09 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_09 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_09;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_10 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('10');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_10 on PROSESS_TASK_PARTITION_FERDIG_10 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_10 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_10 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_10;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_11 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('11');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_11 on PROSESS_TASK_PARTITION_FERDIG_11 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_11 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_11 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_11;

CREATE TABLE PROSESS_TASK_PARTITION_FERDIG_12 PARTITION OF PROSESS_TASK_PARTITION_FERDIG
    FOR VALUES IN ('12');
create UNIQUE index PK_PROSESS_TASK_PARTITION_FERDIG_12 on PROSESS_TASK_PARTITION_FERDIG_12 (ID);
alter table PROSESS_TASK_PARTITION_FERDIG_12 add constraint PK_PROSESS_TASK_PARTITION_FERDIG_12 primary key using index PK_PROSESS_TASK_PARTITION_FERDIG_12;

Insert into PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,FEILHANDTERING_ALGORITME,BESKRIVELSE,CRON_EXPRESSION) values ('batch.partitionCleanBucket','Retry av feilendetasks',1,30,'DEFAULT','Kjører alle feilende tasks i henhold til cron-expreesion','0 0 7 1 * *');
