ALTER TABLE IF EXISTS UNG_GR_STARTDATO RENAME TO GR_STARTDATO;
ALTER SEQUENCE IF EXISTS SEQ_UNG_GR_STARTDATO RENAME TO SEQ_GR_STARTDATO;

ALTER TABLE IF EXISTS UNG_STARTDATOER RENAME TO STARTDATOER;
ALTER SEQUENCE IF EXISTS SEQ_UNG_STARTDATOER RENAME TO SEQ_STARTDATOER;

ALTER TABLE IF EXISTS UNG_SOEKT_STARTDATO RENAME COLUMN UNG_STARTDATOER_ID TO STARTDATOER_ID;
ALTER TABLE IF EXISTS UNG_SOEKT_STARTDATO RENAME TO SOEKT_STARTDATO;
ALTER SEQUENCE IF EXISTS SEQ_UNG_SOEKT_STARTDATO RENAME TO SEQ_SOEKT_STARTDATO;



