ALTER TABLE KONTROLLERT_INNTEKT_PERIODE ADD COLUMN HJEMMEL VARCHAR(100);
UPDATE KONTROLLERT_INNTEKT_PERIODE SET HJEMMEL = 'UNG_FRSKRFT_11' WHERE HJEMMEL IS NULL;
ALTER TABLE KONTROLLERT_INNTEKT_PERIODE ALTER COLUMN HJEMMEL SET NOT NULL;

ALTER TABLE UNG_SATS_PERIODE ADD COLUMN HJEMMEL VARCHAR(100);
UPDATE UNG_SATS_PERIODE SET HJEMMEL = 'UNG_FRSKRFT_9' WHERE HJEMMEL IS NULL;
ALTER TABLE UNG_SATS_PERIODE ALTER COLUMN HJEMMEL SET NOT NULL;

ALTER TABLE UNG_UTTAK_PERIODE ADD COLUMN HJEMMEL VARCHAR(100);
UPDATE UNG_UTTAK_PERIODE SET HJEMMEL = 'UNG_FRSKRFT_6' WHERE HJEMMEL IS NULL;
ALTER TABLE UNG_UTTAK_PERIODE ALTER COLUMN HJEMMEL SET NOT NULL;
