
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-ung-stonadstatistikk-v1
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 2160 # 90 dager
    maxMessageBytes: 5242880 # 5MB
  acl:
    - team: k9saksbehandling
      application: ung-sak
      access: write
    - team: dv-familie
      application: dvh-fampp-konsumer
      access: read
    - team: dv-familie
      application: dvh-familie-konsument
      access: read
