
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-k9-stonadstatistikk-v1
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 2160
  acl:
    - team: k9saksbehandling
      application: k9-sak
      access: write
    - team: dv-familie
      application: dvh-fampp-konsumer
      access: read

