apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aksjonspunkthendelse
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 720 # 30 dager
  acl:
    - team: k9saksbehandling
      application: k9-sak
      access: write
    - team: k9saksbehandling
      application: k9-los-api
      access: read
