apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: vedtakhendelse
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 2160 # 90 dager
  acl:
    - team: k9saksbehandling
      application: k9-sak
      access: write
    - team: k9saksbehandling
      application: k9-statistikk
      access: read
    - team: k9saksbehandling
      application: k9-formidling-dokumentdata
      access: read
    - team: k9saksbehandling
      application: k9-tilbake
      access: read
