apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ung-vedtakhendelse
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 1440  # 60 dager (24*60)
  acl:
    - team: k9saksbehandling
      application: ung-sak
      access: write
    - team: k9saksbehandling
      application: ung-tilbake
      access: read
