CREATE DATABASE "K9-OPPDRAG-UNIT";
CREATE USER "K9-OPPDRAG-UNIT" WITH PASSWORD 'K9-OPPDRAG-UNIT';
GRANT ALL PRIVILEGES ON DATABASE "K9-OPPDRAG-UNIT" TO "K9-OPPDRAG-UNIT";

CREATE DATABASE "K9-OPPDRAG";
CREATE USER "K9-OPPDRAG" WITH PASSWORD 'K9-OPPDRAG';
GRANT ALL PRIVILEGES ON DATABASE "K9-OPPDRAG" TO "K9-OPPDRAG";
