DROP INDEX UIDX_ETTERLYSNING_01;
DROP INDEX UIDX_ETTERLYSNING_02;
DROP INDEX UIDX_ETTERLYSNING_03;
DROP INDEX UIDX_ETTERLYSNING_04;

CREATE UNIQUE INDEX UIDX_ETTERLYSNING_01 ON ETTERLYSNING (fagsak_id, behandling_id, dokument_mal, ARBEIDSGIVER_AKTOR_ID, ARBEIDSGIVER_ORGNR, FOM, TOM);
