ALTER TABLE UNG_SATS_PERIODE
ADD COLUMN SATS_TYPE VARCHAR(100);

UPDATE UNG_SATS_PERIODE SET SATS_TYPE = 'HOY"' where grunnbeløp_faktor = 2;
UPDATE UNG_SATS_PERIODE SET SATS_TYPE = 'LAV' where grunnbeløp_faktor != 2;


ALTER TABLE UNG_SATS_PERIODE ALTER COLUMN SATS_TYPE SET NOT NULL;
