ALTER TABLE UNG_UNGDOMSPROGRAMPERIODE
ADD COLUMN SATS_TYPE VARCHAR(100);

UPDATE UNG_UNGDOMSPROGRAMPERIODE SET SATS_TYPE = 'HOEY' where grunnbeløp_faktor = 2;
UPDATE UNG_UNGDOMSPROGRAMPERIODE SET SATS_TYPE = 'LAV' where grunnbeløp_faktor != 2;


ALTER TABLE UNG_UNGDOMSPROGRAMPERIODE ALTER COLUMN SATS_TYPE SET NOT NULL;
