create table if not exists OLP_VURDERT_OPPLAERING_PERIODE_ANVENDT_DOKUMENT
(
    PLEIETRENGENDE_SYKDOM_DOKUMENT_ID   BIGINT                                      NOT NULL,
    VURDERT_OPPLAERING_PERIODE_ID       BIGINT                                      NOT NULL,
    OPPRETTET_AV                        VARCHAR(20)     DEFAULT 'VL'                NOT NULL,
    OPPRETTET_TID                       TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    CONSTRAINT FK_OLP_VURDERT_OPPLAERING_PERIODE_ANVENDT_DOKUMENT_1 FOREIGN KEY (PLEIETRENGENDE_SYKDOM_DOKUMENT_ID) REFERENCES pleietrengende_sykdom_dokument(ID),
    CONSTRAINT FK_OLP_VURDERT_OPPLAERING_PERIODE_ANVENDT_DOKUMENT_2 FOREIGN KEY (VURDERT_OPPLAERING_PERIODE_ID) REFERENCES olp_vurdert_opplaering_periode(ID)
);
create unique index UIDX_OLP_VURDERT_OPPLAERING_PERIODE_ANVENDT_DOKUMENT_1 ON OLP_VURDERT_OPPLAERING_PERIODE_ANVENDT_DOKUMENT (PLEIETRENGENDE_SYKDOM_DOKUMENT_ID, VURDERT_OPPLAERING_PERIODE_ID);

create table if not exists OLP_VURDERT_OPPLAERING_ANVENDT_DOKUMENT
(
    PLEIETRENGENDE_SYKDOM_DOKUMENT_ID   BIGINT                                      NOT NULL,
    VURDERT_OPPLAERING_ID       BIGINT                                      NOT NULL,
    OPPRETTET_AV                        VARCHAR(20)     DEFAULT 'VL'                NOT NULL,
    OPPRETTET_TID                       TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    CONSTRAINT FK_OLP_VURDERT_OPPLAERING_ANVENDT_DOKUMENT_1 FOREIGN KEY (PLEIETRENGENDE_SYKDOM_DOKUMENT_ID) REFERENCES pleietrengende_sykdom_dokument(ID),
    CONSTRAINT FK_OLP_VURDERT_OPPLAERING_ANVENDT_DOKUMENT_2 FOREIGN KEY (VURDERT_OPPLAERING_ID) REFERENCES olp_vurdert_opplaering(ID)
);
create unique index UIDX_OLP_VURDERT_OPPLAERING_ANVENDT_DOKUMENT_1 ON OLP_VURDERT_OPPLAERING_ANVENDT_DOKUMENT (PLEIETRENGENDE_SYKDOM_DOKUMENT_ID, VURDERT_OPPLAERING_ID);
