CREATE TABLE TMP_FIKS_AKTIV_ET_1 AS (
  SELECT ID
  FROM PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE p1
  WHERE EXISTS (
    SELECT *
    FROM PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE p2
    WHERE p1.ID < p2.ID
      AND p1.PLEIETRENGENDE_AKTOER_ID = p2.PLEIETRENGENDE_AKTOER_ID
      AND p1.AKTIV = true
      AND p2.AKTIV = true
  )
);

UPDATE PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE
SET AKTIV = false
WHERE ID IN (
  SELECT ID FROM TMP_FIKS_AKTIV_ET_1
);


CREATE TABLE TMP_FIKS_AKTIV_ET_2 AS (
  SELECT ID
  FROM PSB_GR_UNNTAK_ETABLERT_TILSYN p1
  WHERE EXISTS (
    SELECT *
    FROM PSB_GR_UNNTAK_ETABLERT_TILSYN p2
    WHERE p1.ID < p2.ID
      AND p1.BEHANDLING_ID = p2.BEHANDLING_ID
      AND p1.AKTIV = true
      AND p2.AKTIV = true
  )
);

UPDATE PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE
SET AKTIV = false
WHERE ID IN (
  SELECT ID FROM TMP_FIKS_AKTIV_ET_2
);

CREATE UNIQUE INDEX IF NOT EXISTS UIDX_2_PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE ON PSB_UNNTAK_ETABLERT_TILSYN_PLEIETRENGENDE (PLEIETRENGENDE_AKTOER_ID) WHERE (aktiv = true);
CREATE UNIQUE INDEX IF NOT EXISTS UIDX_2_PSB_GR_UNNTAK_ETABLERT_TILSYN ON PSB_GR_UNNTAK_ETABLERT_TILSYN (BEHANDLING_ID) WHERE (aktiv = true);
