alter table if exists SYKDOM_PERSON rename to PERSON;
ALTER SEQUENCE if exists seq_sykdom_person RENAME TO seq_person;

alter table if exists SYKDOM_VURDERINGER rename column syk_person_id to pleietrengende_person_id;
alter table if exists SYKDOM_VURDERINGER rename constraint "fk_sykdom_vurderinger_01" to "fk_pleietrengende_sykdom_01";
alter index if exists "sykdom_vurderinger_pkey" rename to "pleietrengende_sykdom_pkey";
alter index if exists "sykdom_vurderinger_syk_person_id_key" rename to "pleietrengende_sykdom_pleietrengende_person_id_key";
ALTER SEQUENCE if exists seq_sykdom_vurderinger RENAME TO seq_pleietrengende_sykdom;
alter table if exists SYKDOM_VURDERINGER rename to PLEIETRENGENDE_SYKDOM;

-- diagnoser
alter table if exists SYKDOM_DIAGNOSEKODER rename column sykdom_vurderinger_id to pleietrengende_sykdom_id;
alter table if exists SYKDOM_DIAGNOSEKODER rename constraint "fk_sykdom_diagnosekoder_01" to "fk_pleietrengende_sykdom_diagnoser_01";
alter index if exists "sykdom_diagnosekoder_pkey" rename to "pleietrengende_sykdom_diagnoser_pkey";
alter index if exists "sykdom_diagnosekoder_sykdom_vurderinger_id_versjon_key" rename to "pleietrengende_syk_diag_pleietrengende_sykdom_id_versjon_key";
ALTER SEQUENCE if exists seq_sykdom_diagnosekoder RENAME TO seq_pleietrengende_sykdom_diagnoser;
alter table if exists SYKDOM_DIAGNOSEKODER rename to PLEIETRENGENDE_SYKDOM_DIAGNOSER;

alter table if exists SYKDOM_DIAGNOSEKODE rename column sykdom_diagnosekoder_id to pleietrengende_sykdom_diagnoser_id;
alter index if exists "sykdom_diagnosekode_pkey" rename to "pleietrengende_sykdom_diagnose_pkey";
alter index if exists "sykdom_diagnosekode_sykdom_diagnosekoder_id_diagnosekode_key" rename to "pleietrengende_sykdom_diagnose_diagnoser_id_diagnosekode_key";
alter table if exists SYKDOM_DIAGNOSEKODE rename constraint "fk_sykdom_diagnosekode_01" to "fk_pleietrengende_sykdom_diagnose_01";
ALTER SEQUENCE if exists seq_sykdom_diagnosekode RENAME TO seq_pleietrengende_sykdom_diagnose;
alter table if exists SYKDOM_DIAGNOSEKODE rename to PLEIETRENGENDE_SYKDOM_DIAGNOSE;

-- vurderinger
alter table if exists SYKDOM_VURDERING rename column sykdom_vurderinger_id to pleietrengende_sykdom_id;
alter index if exists sykdom_vurdering_pkey rename to pleietrengende_sykdom_vurdering_pkey;
alter index if exists sykdom_vurdering_sykdom_vurderinger_id_rangering_type_key rename to pleietrengende_sykdom_vurdering_vurdid_rangering_type_key;
alter table if exists SYKDOM_VURDERING rename constraint fk_sykdom_vurdering_01 to fk_pleietrengende_sykdom_vurdering_01;
ALTER SEQUENCE if exists seq_sykdom_vurdering RENAME TO seq_pleietrengende_sykdom_vurdering;
alter table if exists SYKDOM_VURDERING rename to PLEIETRENGENDE_SYKDOM_VURDERING;

alter table if exists SYKDOM_VURDERING_VERSJON rename column sykdom_vurdering_id to pleietrengende_sykdom_vurdering_id;
alter table if exists SYKDOM_VURDERING_VERSJON rename column endret_for_person_id to endret_for_soeker;
alter table if exists SYKDOM_VURDERING_VERSJON rename column endret_saksnummer to endret_for_soekers_saksnummer;
alter table if exists SYKDOM_VURDERING_VERSJON rename column endret_behandling_uuid to endret_for_soekers_behandling_uuid;
alter index if exists sykdom_vurdering_versjon_pkey rename to pleietrengende_sykdom_vurdering_versjon_pkey;
alter index if exists sykdom_vurdering_versjon_sykdom_vurdering_id_versjon_key rename to pleietrengende_sykdom_vurdering_versjon_vurdid_versjon_key;
alter table if exists SYKDOM_VURDERING_VERSJON rename constraint fk_sykdom_vurdering_versjon_01 to fk_pleietrengende_sykdom_vurdering_versjon_01;
alter table if exists SYKDOM_VURDERING_VERSJON rename constraint fk_sykdom_vurdering_versjon_02 to fk_pleietrengende_sykdom_vurdering_versjon_02;
ALTER SEQUENCE if exists seq_sykdom_vurdering_versjon RENAME TO seq_pleietrengende_sykdom_vurdering_versjon;
alter table if exists SYKDOM_VURDERING_VERSJON rename to PLEIETRENGENDE_SYKDOM_VURDERING_VERSJON;

alter table if exists SYKDOM_VURDERING_PERIODE rename column sykdom_vurdering_versjon_id to pleietrengende_sykdom_vurdering_versjon_id;
alter index if exists sykdom_vurdering_periode_pkey rename to pleietrengende_sykdom_vurdering_versjon_periode_pkey;
alter table if exists SYKDOM_VURDERING_PERIODE rename constraint fk_sykdom_vurdering_periode_01 to fk_pleietrengende_sykdom_vurdering_versjon_periode_01;
ALTER SEQUENCE if exists seq_sykdom_vurdering_periode RENAME TO seq_pleietrengende_sykdom_vurdering_versjon_periode;
alter table if exists SYKDOM_VURDERING_PERIODE rename to PLEIETRENGENDE_SYKDOM_VURDERING_VERSJON_PERIODE;

alter table if exists SYKDOM_VURDERING_VERSJON_BESLUTTET rename column sykdom_vurdering_versjon_id to pleietrengende_sykdom_vurdering_versjon_id;
alter index if exists sykdom_vurdering_versjon_besluttet_pkey rename to pleietrengende_sykdom_vurdering_versjon_besluttet_pkey;
alter table if exists SYKDOM_VURDERING_VERSJON_BESLUTTET rename constraint fk_sykdom_vurdering_versjon_besluttet_01 to fk_pleietrengende_sykdom_vurdering_versjon_besluttet_01;
alter table if exists SYKDOM_VURDERING_VERSJON_BESLUTTET rename to PLEIETRENGENDE_SYKDOM_VURDERING_VERSJON_BESLUTTET;

-- innleggelser
alter table if exists SYKDOM_INNLEGGELSER rename column sykdom_vurderinger_id to pleietrengende_sykdom_id;
alter index if exists sykdom_innleggelser_pkey rename to pleietrengende_sykdom_innleggelser_pkey;
alter index if exists sykdom_innleggelser_sykdom_vurderinger_id_versjon_key rename to pleietrengende_sykdom_innleggelser_sykdom_id_versjon_key;
ALTER SEQUENCE if exists seq_sykdom_innleggelser RENAME TO seq_pleietrengende_sykdom_innleggelser;
alter table if exists SYKDOM_INNLEGGELSER rename to PLEIETRENGENDE_SYKDOM_INNLEGGELSER;

alter table if exists SYKDOM_INNLEGGELSE_PERIODE rename column sykdom_innleggelser_id to pleietrengende_sykdom_innleggelser_id;
alter index if exists sykdom_innleggelse_periode_pkey rename to pleietrengende_sykdom_innleggelse_periode_pkey;
alter table if exists SYKDOM_INNLEGGELSE_PERIODE rename constraint fk_sykdom_innleggelse_periode_01 to fk_pleietrengende_sykdom_innleggelse_periode_01;
ALTER SEQUENCE if exists seq_sykdom_innleggelse_periode RENAME TO seq_pleietrengende_sykdom_innleggelse_periode;
alter table if exists SYKDOM_INNLEGGELSE_PERIODE rename to PLEIETRENGENDE_SYKDOM_INNLEGGELSE_PERIODE;

-- dokumenter
alter table if exists SYKDOM_DOKUMENT rename column sykdom_vurderinger_id to pleietrengende_sykdom_id;
alter table if exists SYKDOM_DOKUMENT rename column behandling_uuid to soekers_behandling_uuid;
alter table if exists SYKDOM_DOKUMENT rename column saksnummer to soekers_saksnummer;
alter table if exists SYKDOM_DOKUMENT rename column person_id to soekers_person_id;
alter index if exists sykdom_dokument_pkey rename to pleietrengende_sykdom_dokument_pkey;
alter index if exists sykdom_dokument_journalpost_id_dokument_info_id_key rename to pleietrengende_sykdom_dokument_journalpost_dokument_info_id_key;
ALTER SEQUENCE if exists seq_sykdom_dokument RENAME TO seq_pleietrengende_sykdom_dokument;
alter table if exists SYKDOM_DOKUMENT rename to PLEIETRENGENDE_SYKDOM_DOKUMENT;

alter table if exists SYKDOM_DOKUMENT_HAR_OPPDATERT_EKSISTERENDE_VURDERINGER rename column sykdom_dokument_id to pleietrengende_sykdom_dokument_id;
alter index if exists sykdom_dokument_har_oppdatert_eksisterende_vurderinger_pkey rename to pleietrengende_sykdom_dokument_har_oppdatert_vurderinger_pkey;
alter table if exists SYKDOM_DOKUMENT_HAR_OPPDATERT_EKSISTERENDE_VURDERINGER rename constraint fk_sykdom_dokument_har_oppdatert_eksisterende_vurderinger_01 to fk_pleietrengende_sykdom_dokument_har_oppdatert_vurderinger_01;
alter table if exists SYKDOM_DOKUMENT_HAR_OPPDATERT_EKSISTERENDE_VURDERINGER rename to PLEIETRENGENDE_SYKDOM_DOKUMENT_HAR_OPPDATERT_VURDERINGER;

alter table if exists SYKDOM_DOKUMENT_INFORMASJON rename column sykdom_dokument_id to pleietrengende_sykdom_dokument_id;
alter table if exists SYKDOM_DOKUMENT_INFORMASJON rename column duplikat_av_sykdom_dokument_id to duplikat_av_pleietrengende_sykdom_dokument_id;
alter index if exists sykdom_dokument_informasjon_pkey rename to pleietrengende_sykdom_dokument_informasjon_pkey;
alter index if exists sykdom_dokument_informasjon_sykdom_dokument_id_versjon_key rename to pleietrengende_sykdom_dokument_informasjon_dok_id_versjon_key;
alter table if exists SYKDOM_DOKUMENT_INFORMASJON rename constraint fk_sykdom_dokument_informasjon to fk_pleietrengende_sykdom_dokument_informasjon_01;
alter table if exists SYKDOM_DOKUMENT_INFORMASJON add constraint fk_pleietrengende_sykdom_dokument_informasjon_02 foreign key (duplikat_av_pleietrengende_sykdom_dokument_id) references pleietrengende_sykdom_dokument(id);
ALTER SEQUENCE if exists seq_sykdom_dokument_informasjon RENAME TO seq_pleietrengende_sykdom_dokument_informasjon;
alter table if exists SYKDOM_DOKUMENT_INFORMASJON rename to PLEIETRENGENDE_SYKDOM_DOKUMENT_INFORMASJON;

-- grunnlag
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename column sykdom_grunnlag_id to medisinsk_grunnlagsdata_id;
alter index if exists sykdom_grunnlag_behandling_pkey rename to gr_medisinsk_pkey;
alter index if exists sykdom_grunnlag_behandling_behandling_uuid_versjon_key rename to gr_medisinsk_id_behandling_uuid_versjon_key;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename constraint sykdom_grunnlag_behandling_saksnummer_behandlingsnummer_ver_key to gr_medisinsk_id_saksnummer_behandlingsnummer_ver_key;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename constraint fk_sykdom_grunnlag_behandling_01 to fk_gr_medisinsk_01;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename constraint fk_sykdom_grunnlag_behandling_02 to fk_gr_medisinsk_02;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename constraint fk_sykdom_grunnlag_behandling_03 to fk_gr_medisinsk_03;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING add constraint fk_gr_medisinsk_04 foreign key (behandling_uuid) references behandling(uuid);
ALTER SEQUENCE if exists seq_sykdom_grunnlag_behandling RENAME TO seq_gr_medisinsk;
alter table if exists SYKDOM_GRUNNLAG_BEHANDLING rename to GR_MEDISINSK;

-- grunnlagsdata
alter table if exists SYKDOM_GRUNNLAG rename column sykdom_grunnlag_uuid to sporingsreferanse;
alter table if exists SYKDOM_GRUNNLAG rename column sykdom_innleggelser_id to pleietrengende_sykdom_innleggelser_id;
alter table if exists SYKDOM_GRUNNLAG rename column sykdom_diagnosekoder_id to pleietrengende_sykdom_diagnoser_id;
alter index if exists sykdom_grunnlag_pkey rename to medisinsk_grunnlagsdata_pkey;
alter index if exists sykdom_grunnlag_sykdom_grunnlag_uuid_key rename to medisinsk_grunnlagsdata_uuid_key;
alter table if exists SYKDOM_GRUNNLAG rename constraint fk_sykdom_grunnlag_01 to fk_medisinsk_grunnlagsdata_01;
alter table if exists SYKDOM_GRUNNLAG rename constraint fk_sykdom_grunnlag_02 to fk_medisinsk_grunnlagsdata_02;
ALTER SEQUENCE if exists seq_sykdom_grunnlag RENAME TO seq_medisinsk_grunnlagsdata;
alter table if exists SYKDOM_GRUNNLAG rename to MEDISINSK_GRUNNLAGSDATA;

-- koblinger
alter table if exists SYKDOM_VURDERING_VERSJON_DOKUMENT rename column sykdom_dokument_id to pleietrengende_sykdom_dokument_id;
alter table if exists SYKDOM_VURDERING_VERSJON_DOKUMENT rename column sykdom_vurdering_versjon_id to pleietrengende_sykdom_vurdering_versjon_id;
alter index if exists sykdom_vurdering_versjon_doku_sykdom_dokument_id_sykdom_vur_key rename to pleietrengende_sykdom_vurdering_versjon_dokument_id_vv_key;
alter table if exists SYKDOM_VURDERING_VERSJON_DOKUMENT rename constraint fk_sykdom_vurdering_versjon_dokument_01 to pleietrengende_sykdom_vurdering_versjon_dokument_01;
alter table if exists SYKDOM_VURDERING_VERSJON_DOKUMENT rename constraint fk_sykdom_vurdering_versjon_dokument_02 to pleietrengende_sykdom_vurdering_versjon_dokument_02;
alter table if exists SYKDOM_VURDERING_VERSJON_DOKUMENT rename to PLEIETRENGENDE_SYKDOM_VURDERING_VERSJON_ANVENDT_DOKUMENT;

alter table if exists SYKDOM_GRUNNLAG_DOKUMENT rename column sykdom_grunnlag_id to medisinsk_grunnlagsdata_id;
alter table if exists SYKDOM_GRUNNLAG_DOKUMENT rename column sykdom_dokument_id to pleietrengende_sykdom_dokument_id;
alter index if exists sykdom_grunnlag_dokument_sykdom_grunnlag_id_sykdom_dokument_key rename to medisinsk_grunnlagsdata_godkj_legeerklaeringer_grlg_dok_key;
alter table if exists SYKDOM_GRUNNLAG_DOKUMENT rename constraint fk_sykdom_grunnlag_dokument_01 to fk_medisinsk_grunnlagsdata_godkjente_legeerklaeringer_01;
alter table if exists SYKDOM_GRUNNLAG_DOKUMENT rename constraint fk_sykdom_grunnlag_dokument_02 to fk_medisinsk_grunnlagsdata_godkjente_legeerklaeringer_02;
alter table if exists SYKDOM_GRUNNLAG_DOKUMENT rename to MEDISINSK_GRUNNLAGSDATA_GODKJENTE_LEGEERKLAERINGER;

alter table if exists SYKDOM_GRUNNLAG_VURDERING rename column sykdom_grunnlag_id to medisinsk_grunnlagsdata_id;
alter table if exists SYKDOM_GRUNNLAG_VURDERING rename column sykdom_vurdering_versjon_id to pleietrengende_sykdom_vurdering_versjon_id;
alter index if exists sykdom_grunnlag_vurdering_sykdom_grunnlag_id_sykdom_vurderi_key rename to medisinsk_grunnlagsdata_gjeldende_vurderinger_grunnlag_vv_key;
alter table if exists SYKDOM_GRUNNLAG_VURDERING rename constraint fk_sykdom_grunnlag_vurdering_01 to fk_medisinsk_grunnlagsdata_gjeldende_vurderinger_01;
alter table if exists SYKDOM_GRUNNLAG_VURDERING rename constraint fk_sykdom_grunnlag_vurdering_02 to fk_medisinsk_grunnlagsdata_gjeldende_vurderinger_02;
alter table if exists SYKDOM_GRUNNLAG_VURDERING rename to MEDISINSK_GRUNNLAGSDATA_GJELDENDE_VURDERINGER;

drop sequence if exists seq_sykdom_dokument_sak;
drop sequence if exists seq_sykdom_grunnlag_dokument;
drop sequence if exists seq_sykdom_grunnlag_vurdering;
drop sequence if exists seq_sykdom_vurdering_versjon_dokument;
