DROP SEQUENCE IF EXISTS SEQ_BG_NAERING_INNTEKT_PERIODE;
DROP INDEX IF EXISTS IDX_BG_NAERING_INNTEKT_PERIODE_01;
DROP INDEX IF EXISTS UIDX_BG_NAERING_INNTEKT_PERIODE_01;
DROP INDEX IF EXISTS UIDX_BG_NAERING_INNTEKT_PERIODE_02;
DROP TABLE IF EXISTS BG_NAERING_INNTEKT_PERIODE;

ALTER TABLE IF EXISTS gr_beregningsgrunnlag
DROP COLUMN IF EXISTS bg_naering_inntekt_id;
DROP SEQUENCE IF EXISTS SEQ_BG_NAERING_INNTEKT_PERIODER;
DROP TABLE IF EXISTS BG_NAERING_INNTEKT_PERIODER;
