
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'AT' where AKTIVITET is null AND AKTIVITET_TYPE = '0';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'SN' where AKTIVITET is null AND AKTIVITET_TYPE = '1';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'FL' where AKTIVITET is null AND AKTIVITET_TYPE = '2';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'DP' where AKTIVITET is null AND AKTIVITET_TYPE = '3';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'BA' where AKTIVITET is null AND AKTIVITET_TYPE = '4';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'MIDL_INAKTIV' where AKTIVITET is null AND AKTIVITET_TYPE = '5';
update OMP_OPPGITT_FRAVAER_PERIODE set AKTIVITET = 'ANNET' where AKTIVITET is null AND AKTIVITET_TYPE = '6';

alter table OMP_OPPGITT_FRAVAER_PERIODE alter column aktivitet_type DROP NOT NULL;

alter table OMP_OPPGITT_FRAVAER_PERIODE alter column aktivitet set NOT NULL;
