package no.nav.ung.kodeverk.hendelse;

public enum EventHendelse {
    AKSJONSPUNKT_OPPRETTET,
    AKSJONSPUNKT_UTFØRT,
    AKSJONSPUNKT_TILBAKEFØR,
    AKSJONSPUNKT_AVBRUTT,
    AKSJONSPUNKT_HAR_ENDRET_BEHANDLENDE_ENHET,
    BEHANDLINGSKONTROLL_EVENT,
    VASKEEVENT,
    HASTESAK_MERKNAD_NY,
    HASTESAK_MERKNAD_FJERNET
}
