name: Bygg pull request

on: [pull_request]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: init postgres
        run: |
          export PGPASSWORD='postgres'
          psql -h localhost -p 5432 -U 'postgres' <<EOSQL
            CREATE DATABASE k9sak_unit;
            CREATE USER k9sak_unit WITH PASSWORD 'k9sak_unit';
            GRANT ALL PRIVILEGES ON DATABASE k9sak_unit TO k9sak_unit;
            \connect k9sak_unit;
            create extension if not exists btree_gist;
          EOSQL
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.11

      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn dependency:go-offline --batch-mode --settings ./.github/.m2/settings.xml --file pom.xml -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
          mvn package -U --batch-mode --settings ./.github/.m2/settings.xml --file pom.xml -DtrimStackTrace=false -Dchangelist= -Dsha1=-$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          DATASOURCE_HOST: localhost
          DATASOURCE_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port

