name: Sonar analyse

on: 
  push:
    branches:
    - 'feature/sonarcloud'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: k9sak_unit
          POSTGRES_PASSWORD: k9sak_unit
          POSTGRES_DB: k9sak_unit
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn clean verify sonar:sonar -Djacoco.skip=false --batch-mode --settings ./.github/.m2/settings.xml --file pom.xml
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          DATASOURCE_HOST: localhost
