# This workflow is triggered by GitHub Copilot to set up
# the environment for the coding agent.
# https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent

name: Copilot Setup Steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: navikt/sif-gha-workflows/.github/actions/maven/setup-java-and-maven@main # ratchet:exclude
        with:
          github-token: ${{ secrets.READER_TOKEN }} # bruker READER_TOKEN pga private repos
          java-version: 25

      - run: mvn dependency:resolve -s settings.xml
