name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      environment:
        required: true
        type: choice
        description: 'The environment to deployed to (dev|prod)'
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ inputs.image }}
      cluster: ${{ inputs.environment }}-gcp
      naiserator_file: deploy/${{ inputs.environment }}-gcp.yml
      namespace: k9saksbehandling
    secrets: inherit
