name: Create or update Kafka topics

on:
  push:
    paths:
      - 'deploy/kafka/**'

jobs:
  deploy-kafka-topics-dev:
    name: Deploy to Aiven Dev
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/kafka/aapen-k9-stonadstatistikk-v1-dev.yml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/kafka/aksjonspunkthendelse-dev.yml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/kafka/k9-vedtakhendelse-dev.yml

  deploy-kafka-topics-prod:
    name: Deploy to Aiven Prod
    if: startsWith(github.ref, 'refs/heads/master')  # If the branch is master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/kafka/aapen-k9-stonadstatistikk-v1-prod.yml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/kafka/aksjonspunkthendelse-prod.yml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/kafka/k9-vedtakhendelse-prod.yml
