name: Create or update Kafka topics

on:
  push:
    paths:
      - 'deploy/topics.yml'
      - 'deploy/topics-q.yml'

jobs:
  deploy-kafka-topics-dev:
    name: Deploy to Aiven Dev
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: deploy/topics-q.yml

  deploy-kafka-topics-prod:
    name: Deploy to Aiven Prod
    if: startsWith(github.ref, 'refs/heads/master')  # If the branch is master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-gcp
          VAR: kafka-pool=nav-prod
          RESOURCE: deploy/topics.yml
