name: Create or update kafka topic

on:
  workflow_dispatch:
    inputs:
      topic:
        type: choice
        description: Choose topic to deploy
        required: true
        options:
          - topic-aksjonspunkthendelse.yml
          - topic-infotrygdfeedhendelse.yml
          - topic-stonadsstatistikk.yml
          - topic-vedtakhendelse.yml
          - topic-dokumenthendelse.yml
      prod:
        type: boolean
        description: Deploy to prod
        required: true

jobs:
  deploy-kafka-topics:
    name: Deploy ${{ github.event.inputs.topic }} to Aiven Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: deploy/kafka/${{ github.event.inputs.topic }}

      - name: Deploy to Prod
        if: ${{ github.event.inputs.prod == 'true' }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: prod-gcp
          VAR: kafka-pool=nav-prod
          RESOURCE: deploy/kafka/${{ github.event.inputs.topic }}
