name: "Pull Request Labeler"
on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
