name: Openapi generate

on:
  push:
    branches:
      # While testing we trigger on this feature branch. Change to master when done.
      - TSFF-236-mvn-generate-openapi
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - 'dev/**'
  workflow_dispatch:

jobs:
  build:
    name: Generer og commit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set variables
        run: |
          echo "TIMESTAMP=$(expr $(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV
                - uses: navikt/github-app-token-generator@v1.2
      - uses: navikt/github-app-token-generator@v1.2
        name: Cross repo token
        id: get-token
        with:
          private-key: ${{ secrets.K9SAKSBEHANDLING_PRIVATE_KEY }}
          app-id: ${{ secrets.K9SAKSBEHANDLING_APP_ID }}
      - uses: actions/checkout@v4
        with:
          path: k9-sak
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Openapi generate
        shell: bash
        working-directory: k9-sak
        run: |
          ./dev/generate-openapi-json.sh
          echo "TAG=$TIMESTAMP-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Sjekk ut k9-sak-typescript-client
        uses: actions/checkout@v4
        with:
          repository: navikt/k9-sak-typescript-client
          ref: 'k9-sak-workflow' # Maybe just use main later
          token: ${{ steps.get-token.outputs.token }}
          path: k9-sak-typescript-client
          fetch-depth: 1
      - name: Kopier ny openapi til klient
        shell: bash
        working-directory: k9-sak
        run: |
          cp web/target/k9-sak.openapi.json ../k9-sak-typescript-client/src/
      - name: Push ny openapi til klient repo
        shell: bash
        working-directory: k9-sak-typescript-client
        env:
          GIT_USER_NAME: "${{ github.actor }}"
          GIT_USER_EMAIL: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          GITHUB_TOKEN: "${{ steps.get-token.outputs.token }}"
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"
          git diff --quiet || (git add -A && git commit -m "k9-sak.openapi.json updated from k9-sak")
          git push
          
