on:
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  promote:
    if: contains(github.event.comment.html_url, '/issues/') && startsWith( github.event.comment.body, '/promote ' )
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge command
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: context.payload.comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1',
            });
      - name: Set variabler for deploy
        shell: bash
        run: |
          echo "TAG=$(echo '${{ github.event.issue.title }}' | awk '{print $NF}' | awk -F- '{print $NF}')" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE_BASE:$(echo '${{  github.event.issue.title }}' | awk '{print $NF}')" >> $GITHUB_ENV
          echo "CLUSTER=$(echo '${{github.event.comment.body}}' | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Sjekk ut kode
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}

      - name: Promoter til cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: deploy/${{ env.CLUSTER }}.yml

      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.issue.number }} }
            github.rest.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: 'promote til ${{ env.CLUSTER }} feilet'})

      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.issue.number }} }
            github.rest.issues.createComment({...issue,
                                    body: 'promote til  ${{ env.CLUSTER }} utført'})
            github.rest.issues.addLabels({...issue, labels: ['deployment','${{ env.CLUSTER }}']})
