name: Snyk
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: init postgres
        run: |
          export PGPASSWORD='postgres'
          psql -h localhost -p 5432 -U 'postgres' <<EOSQL
            CREATE DATABASE k9sak_unit;
            CREATE USER k9sak_unit WITH PASSWORD 'k9sak_unit';
            GRANT ALL PRIVILEGES ON DATABASE k9sak_unit TO k9sak_unit;
            \connect k9sak_unit;
            create extension if not exists btree_gist;
          EOSQL
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: snyk/actions/setup@master

      - name: Create snyk-settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo.maven.apache.org/maven2"
              },
              {
                "id": "github",
                "name": "github",
                "url": "https://maven.pkg.github.com/${{ github.repository }}"
              }
            ]
          servers: |
            [
              {
                "id": "github",
                "password": "${{ secrets.READER_TOKEN }}",
                "username": "${{ github.actor }}"
              }
            ]
          output_file: snyk-settings.xml

      - name: Set TAG for mvn revision
        run: echo "TAG=snyk-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Run mvn clean install
        run: mvn clean install -B -s snyk-settings.xml -DskipTests -Drevision=$TAG

      - name: Run Snyk monitor
        run: >
          snyk monitor
          --org=k9saksbehandling
          --all-projects
          --configuration-attributes=usage:java-runtime
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          --exclude=javax
          -- -s snyk-settings.xml -Drevision=$TAG --fail-never
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
